schema: ./graphql/schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: ' http://localhost:5130/graphql/'
      introspect: true
      headers:
        user-agent: JS GraphQL
